apiVersion: apps/v1   
kind: Deployment
metadata:
  name: primakube
spec:
  replicas: 3
  selector:
    matchLabels:
      app: primakube
      version: v1
  template:
    metadata:
      labels:
        app: primakube
        version: v1
  containers:
  - name: primakube
    image: dpetrolio/argocd1:latest   
    ports:
    - containerPort: 8088  

